name: vulnpy

on:
  push:                                       
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run: echo "This is a build step, or not?"

  test:
    runs-on: ubuntu-latest
    steps:
      - run: echo "This is a test step"